---

- hosts: aws
  remote_user: ubuntu
  become: yes
  become_user: root

  tasks:
    - name: Show contents of authorized_keys file
      shell: cat /home/ubuntu/.ssh/authorized_keys
      register: authorized_keys_content

    - debug:
        msg: "{{ authorized_keys_content.stdout }}"
   
    - name: Check for existence of OTHER, the needed key, in the authorized_keys file
      lineinfile:
        path: "/home/ubuntu/.ssh/authorized_keys"
        state: present
        line: "{{ item }}"
      check_mode: yes
      register: needed_key_is_there
      with_file:
        - public_keys/xyz_sofia_nv.pub3

    - name: Delete the key that is not needed, if the needed key is there
      authorized_key:
        user: ubuntu
        key: '{{ item }}'
        state: absent
      with_file:
        - public_keys/nv_xyz.pub
      when: needed_key_is_there is not changed
