---

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: us-east-1

  vars_files:
    - ../aws_keys.yml
    - ../aws_vars.yml 
  
  tasks:
    - name: Obtain list of instances
      ec2_instance_facts:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        filters:
          "instance-state-name": running
          "instance-type": "t3.small" 
        region: "us-east-1"
      register: ec2_metadata

    - name: Print list of instance's date
      debug: 
        msg: "Instance Name: {{ item.tags['Name'] }} Private IP address: {{ item.private_ip_address }}"
      with_items: 
        - "{{ ec2_metadata.instances }}" 

    - name: Empty the output file
      shell: echo > aws_nv_list_t3_small.txt 
   
    - name: Print results in a txt file
      shell: echo "({{ item.tags['Name'] }}),{{ item.private_ip_address }}" >> aws_nv_list_t3_small.txt 
      with_items:
        - "{{ ec2_metadata.instances }}"
