---

- hosts: aws
  remote_user: ubuntu
  become: yes
  become_user: root

  tasks:
    - name: Check whether swap is already enabled or not
      shell: cat /proc/meminfo | grep SwapTotal | awk '{print $2}' 
      register: present_swap_size

    - name: Check whether swap parameters are set
      shell: cat /etc/sysctl.conf
      register: sysctl_file

    - block:
      - name: Determine the RAM size
        shell: cat /proc/meminfo | grep MemTotal | awk '{print $2}'
        register: mem_size

      - name: Calculate the swap size
        set_fact:
          swap_size: "{{ mem_size.stdout|int * 2 }}"
        when:
          mem_size.stdout|int <= 2097152

      - name: Calculate the swap size
        set_fact:
          swap_size: "{{ 4194304 + (mem_size.stdout|int - 2097152) }}"
        when:
          mem_size.stdout|int > 2097152
 
      - name: create swap file
        command: "fallocate -l {{ swap_size }}KiB  /swapfile"

      - name: change permission type
        file: path=/swapfile mode=600 state=file

      - name: setup swap
        command: mkswap /swapfile
    
      - name: create swap
        command: swapon /swapfile

      - name: Add to fstab
        action: lineinfile dest=/etc/fstab regexp="swapfile" line="/swapfile none swap sw 0 0" state=present

      - name: start swap
        command: swapon -a

      - name: set swapiness
        sysctl:
          name: vm.swappiness
          value: "10"

      - name: set swapiness
        sysctl:
          name: vm.vfs_cache_pressure
          value: "50"

      when: present_swap_size.stdout == "0"

    - block:
      - name: set swapiness to already having swap enabled
        sysctl:
          name: vm.swappiness
          value: "10"

      - name: set swapiness to already having swap enabled
        sysctl:
          name: vm.vfs_cache_pressure
          value: "50"

      when: present_swap_size.stdout != "0" and sysctl_file.stdout.find('swappiness') == -1
